require('settings')
require('mappings')
require('packer-config')
require('colorscheme-config.nightfox')
require('nvim-tree-config')
require('lualine-config')
require('barbar-config')
require('treesitter-config')

require('lsp-config.language-servers')
require('lsp-config.nvim-cmp')
